stages:
  - build
  - test
  - deploy

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  image: maven
  tags:
    - dalfcs_gitlab_docker_ci
  script:
    - mvn compile
  only:
    - master

test:
  stage: test
  image: maven
  tags:
    - dalfcs_gitlab_docker_ci
  script:
    - mvn test
  only:
    - master

deploy:
  stage: deploy
  image: maven
  tags:
    - ugrad
  artifacts:
    paths:
      - target
  script:
    - chmod og-rwx ${DEPLOY_SSH_KEY}
    - ls -lrt
    - zip -r ${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}.zip *
    - scp -r -o StrictHostKeyChecking=no -i ${DEPLOY_SSH_KEY} ${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}.zip ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}.zip
