image: maven:latest

stages:
  - build
  - test

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  tags:
    - dalfcs_gitlab_docker_ci
  image: maven
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test
