stages:
  - build
  - test
  - deploy

cache:
  paths:
    - .m2/repository/
    - target/
    
build:
  stage: build
  image: maven
  tags:
    - dalfcs_gitlab_docker_ci
  script:
    - mvn compile

test:
  stage: test
  image: maven
  tags:
    - dalfcs_gitlab_docker_ci
  script:
    - mvn test

deploy:
  stage: deploy
  image: maven
  tags:
    - dalfcs_gitlab_docker_ci
  script:
    - mvn package
    - ls -lrt
